README.md

Typo fix Readme

---

meeting-notes/2019.05.31_collabsummit_session.md

Checkbox Typo fixes

---

meeting-notes/2019.05.31_collabsummit_session.md

I have tried to write down all the task written on the board.
I don't remember the meaning of some points:
- test
- access to correct wg/tc
The other ones should be covered 👍

add board bullet points

---

proposals/stage0/REQUIREMENTS/README.md

draft: proposal representative requirements

---

meeting-notes/2019.09.10_meeting_notes.md

add meeting notes from sept. 10 meeting

---

README.md

membership: add myles

---

README.md

this is an automated update via ncu-team
As this is automated it does not require review

doc: update member list

---

MEMBER_EXPECTATIONS.md
onboarding.md

This is an initial draft based on the discussions that we had in the last couple of meetings. 
Closes #14

[Initial draft] Defining and documenting the on-boarding process

---

standards-calendar.md

Per the travel process we discussed, I plan to attend the upcoming TC39 plenary.

Add @gibson042 for TC39 plenary 2020-02

---

meeting-notes/2019.12.17_meeting_notes.md
meeting-notes/2020.01.14_meeting_notes.md

Notes for Dec meeting as well as today's meeting

Add missing notes

---

meeting-notes/2020.01.28_meeting_notes.md
meeting-notes/2020.02.25_meeting_notes.md
meeting-notes/2020.03.10_meeting_notes.md

Closes: https://github.com/openjs-foundation/standards/issues/65
Closes: https://github.com/openjs-foundation/standards/issues/63
Closes: https://github.com/openjs-foundation/standards/issues/61

update meetings notes

---

GOVERNANCE.md
MEMBER_EXPECTATIONS.md
README.md

The CPC has ratified that the Standards "team" is now
officially a Working Group. huzzah

Standards is now a real working group

---

meeting-notes/2020.03.23_meeting_notes.md

add meeting notes for march 23 meeting

---

README.md

Add mission statement to top of README

---

README.md

**Hi all! 👋**
I'd like to request your consideration in allowing me join the OpenJS Foundation Standards Working Group.
> Our i18n session at the OpenJS Collaborator's summit in Berlin last year
With the [recent approval](https://github.com/openjs-foundation/standards/issues/43) of the OpenJS Foundation's [liaison membership in the Unicode Consortium](https://home.unicode.org/membership/liaison-members/), there's now an open door between these organizations for enabling resource parity and a relationship that mutually supports each other's projects.
Currently, there are two members of the [Cross Project Council](https://github.com/openjs-foundation/cross-project-council#regular-members) which have significant interest in building this relationship as liaisons: @eemeli, and myself.
@eemeli …

Add new WG member: Ben Michel

---

meeting-notes/2020.04.07_meeting_notes.md
meeting-notes/2020.05.05_meeting_notes.md
meeting-notes/2020.05.19_meeting_notes.md
meeting-notes/2020.06.02_meeting_notes.md
meeting-notes/2020.06.16_meeting_notes.md

Add meeting notes 

---

MEMBER_REPRESENTATION.md

Add representation in the Unicode MessageFormat WG

---

meeting-notes/2020.07.14_meeting_notes.md
meeting-notes/2020.08.25_meeting_notes.md
meeting-notes/2020.09.08_meeting_notes.md
meeting-notes/2020.10.06_meeting_notes.md

chore: add past meeting notes for past meetings

---

meeting-notes/2021.01.12_meeting_notes.md
meeting-notes/2021.01.26_meeting_notes.md
meeting-notes/2021.02.23_meeting_notes.md

Closes #120 
Closes #121 
Closes #124

adds meeting notes from recent meetings

---

meeting-notes/2021.04.20_meeting_notes.md
meeting-notes/2021.05.18_meeting_notes.md
meeting-notes/2021.06.01_meeting_notes.md

Closes #136 
Closes #139 
Closes #140

adds missing meeting notes

---

meeting-notes/2021.06.29_meeting_notes.md
meeting-notes/2021.07.13_meeting_notes.md

adds minutes from last 2 meetings

---

README.md

Per discussion with @jorydotcom

Add Lea Verou to Standards WG members

---

MEMBER_REPRESENTATION.md

Fixes #211
Draft until confirmed by Standards Working Group

Add Lea Verou as a TC39 delegate

---

meeting-notes/2023.03.21_meeting_notes.md
meeting-notes/2023.04.04_meeting_notes.md

Add Meeting Notes

---

README.md

Update remade to have same flavor of CPC repo

chore(readme): add logo  + link of foundation

---

meeting-notes/2023.05.02_meeting_notes.md

Add meeting minutes from May 2 meeting
Closes #227

Minutes from May

---

MEMBER_REPRESENTATION.md

Closes #170.
This is a request to formalize my offer made in #170 to replace @MylesBorins in this role.

Add Tobie Langel as OSI Representative

---

README.md

/cc @jorydotcom @rginn @joesepi

Add @darcyclarke as Active Member

---

MEMBER_REPRESENTATION.md

I'm starting a new position at Deno so I'll be part of their delegation. Farewell friends :cry:

MEMBER_REPRESENTATION: Remove snek

---

README.md

Hi team!
Currently, I am a core member of Express and Node.js. I have been around the standards WG for a while, and I am participating in the TC39 TG3 (Thanks @ctcpip @ljharb). I find the standards universe fascinating and want to get more involved in TC39 in particular.
I would like to formalize my membership to the team. So far, I have been attending the meetings regularly and followed up on the discussions :smile:

Add @UlisesGascon to active members
